### ISSUE TITLE
Back/Paramètres : mettre en place système de désactivation automatique comptes minArm

### ISSUE THREAD

**Issue by Grainedepaillette** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1003]
(cf. système mis en place pour la suppression automatique des comptes candidats #554)

**Procédure de désactivation automatique du compte agent minArm :**

a. SI connexion régulière ALORS aucune action

b. SI absence de connexion 11 mois après la date de la dernière connexion ALORS

i. Envoi d'un 1er courriel automatique :

    Intitulé courriel : [Civils de la Défense] Votre compte utilisateur : mise à jour nécessaire
    Texte : "Bonjour [Prénom/Nom agent]. Nous vous invitons à mettre à jour votre compte utilisateur sur le site Civils de la Défense. Sans mise à jour de celui-ci sous 30 jours, nous vous informons qu'il sera désactivé automatiquement. [Bouton : Mettre à jour] L’équipe Civils de la Défense "

ii. Envoi d'un 2ème courriel automatique (30 jours après envoi du 1er courriel) :

    Intitulé courriel : [Civils de la Défense] Votre compte utilisateur a été désactivé
    Texte : "Bonjour [Prénom/Nom agent]. Nous vous confirmons la désactivation de votre compte utilisateur. Pour accéder à nouveau à l'application, nous vous invitons à saisir le responsable fonctionnel de l'application afin qu'il procède à la réactivation de votre compte. L’équipe Civils de la Défense"

**Comment by btrd** [comment]
Lors de la suppression d'un administrateur que dois-je faire des données suivantes :
- les administrateurs qu'il a invité
- les offres d'emplois qu'il a créé
- les listes de candidats qu'il a créé

**Comment by Grainedepaillette** [comment]
@btrd, il faut conserver ces données car : 

les administrateurs qu'il a invité --> à conserver : les comptes créés peuvent être associés à d'autres offres + la vie de chaque compte utilisateur doit être gérée de manière distincte.  

les offres d'emplois qu'il a créé --> à conserver : on en a besoin pour les stats. Est-ce qu'elles peuvent être conservées mais archivées s'il n'y a pas d'autres comptes employeur tagués dessus ? 

Les listes de candidats --> à supprimer : car les comptes candidats sont susceptibles d'être supprimés et qu'une liste a une durée d'existence et d'utilité relativement courte (entre 6 mois et 1an max).

**Comment by btrd** [comment]
En fait j'ai voulu reprendre ce qu'on a fait pour les utilisateurs (suppression) alors qu'ici on parle seulement de désactivation, je propose donc de garder le comportement actuel lorsqu'on désactive un admin : on garde les données et le seul changement c'est que l'admin ne peut pas se connecter.

**Comment by btrd** [comment]
Disponible ici https://erecrutement-cvd-staging-pr1011.osc-fr1.scalingo.io

On peut se prévoir un créneau pour tester

**Comment by btrd** [comment]
1 jour pour alerte
3 jours suppression

**Comment by btrd** [comment]
@Grainedepaillette C'est en place, j'ai mis 2 jours sans activité pour la suppression et tu es prévenu la veille

**Comment by Grainedepaillette** [comment]
Comptes (BANT, employeur et autre rôle) **crées le 07.07 à tester le 09.07.**

**Comment by Grainedepaillette** [comment]
@btrd C'est opérationnel pour la réception des courriels pour les candidats, en revanche je n'ai rien reçu pour les comptes des admins.

**Comment by Grainedepaillette** [comment]
@btrd Comme convenu, merci de communiquer le nombre et les courriels (si possible) : 
- des comptes candidats qui seront soumis à la procédure de suppression car datés 
- et les comptes admins qui seront soumis à la procédure de désactivation car datés également.

**Comment by btrd** [comment]
S'assurer qu'un courriel d'avertissement soit envoyé avant que le compte soit désactivé.

**Comment by Grainedepaillette** [comment]
@btrd tu confirmes que le système est opérationnel pour les comptes admins ?

**Comment by btrd** [comment]
Oui, je passe en prod ?

**Comment by Grainedepaillette** [comment]
@btrd C'est ok pour le passage en production. 

En revanche pourras-tu comme convenu, communiquer la liste des comptes utilisateurs (admins) qui recevront directement le courriel car inactifs depuis déjà longtemps (cf. échanges ci - dessus).

**Comment by Queenze972** [comment]
@sebastiencarceles, on avait dit qu'il fallait que je fasse une passe sur l'archivage/la désactivation des comptes utilisateurs inactifs depuis 11 mois. Ci dessous les résultats : 

Comportement constaté : Des utilisateurs, jamais connectés, inscrit depuis octobre 2022 ont toujours un compte actif dans le BO.
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/f3cb27b9-592c-4b8f-bad2-35ec134f20dc)

Comportement attendu : a. SI connexion régulière ALORS aucune action

b. SI absence de connexion 11 mois après la date de la dernière connexion ALORS

i. Envoi d'un 1er courriel automatique :

Intitulé courriel : [Civils de la Défense] Votre compte utilisateur : mise à jour nécessaire
Texte : "Bonjour [Prénom/Nom agent]. Nous vous invitons à mettre à jour votre compte utilisateur sur le site Civils de la Défense. Sans mise à jour de celui-ci sous 30 jours, nous vous informons qu'il sera désactivé automatiquement. [Bouton : Mettre à jour] L’équipe Civils de la Défense "

ii. Envoi d'un 2ème courriel automatique (30 jours après envoi du 1er courriel) :

Intitulé courriel : [Civils de la Défense] Votre compte utilisateur a été désactivé
Texte : "Bonjour [Prénom/Nom agent]. Nous vous confirmons la désactivation de votre compte utilisateur. Pour accéder à nouveau à l'application, nous vous invitons à saisir le responsable fonctionnel de l'application afin qu'il procède à la réactivation de votre compte. L’équipe Civils de la Défense"

Sans action de la part des utilisateurs, ces derniers deviennent "inactifs" et n'ont plus la possibilité de se connecter au BO ADMIN. 

Pour la question des données, cf. commentaire de Sarah.

**Comment by sebastiencarceles** [comment]
@Queenze972 ce que je constate dans le code c'est que la fonctionnalité de désactivation des comptes admin est codée, mais qu'elle a été shuntée. En effet : 

```rb
  cond = ENV["DAYS_INACTIVITY_PERIOD_BEFORE_DEACTIVATION"].present?
  cond &&= ENV["DAYS_NOTICE_PERIOD_BEFORE_DEACTIVATION"].present?
  if cond
    every 1.day, "purge_administrators", at: "11:00" do
      Administrator.deactivate_when_too_old
    end
  end
```

Ça dit que tous les jours on désactive les comptes trop vieux, à condition que les variables d'environnement `DAYS_INACTIVITY_PERIOD_BEFORE_DEACTIVATION` et `DAYS_NOTICE_PERIOD_BEFORE_DEACTIVATION` soient définies sur l'instance.

Or, ces variables ne sont définies que pour : 
- erecrutement-cvd-production
- erecrutement-dga-production
- erecrutement-sgdsn-production


Elles ne le sont pas pour les instances : 
- erecrutement-anssi-production
- toutes les applications de staging

Donc si tu as regardé sur la prod de l'ANSSI ou sur une app de staging, alors c'est normal que les comptes ne soient pas désactivés.

Si tu as regardé sur la prod de CVD, DGA ou SGDSN, alors ce n'est pas normal, les comptes devraient être désactivés.

Peux-tu me préciser d'où vient ta capture d'écran ?

Merci

**Comment by Queenze972** [comment]
@sebastiencarceles La capture d'écran provient de la PROD CVD : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/77f21f11-4c10-43bc-8e0a-2b32582145ae)
