### ISSUE TITLE
Back : identifier l'origine des lenteurs (chargement des pages)

### ISSUE THREAD

**Issue by Grainedepaillette** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1004]
1ère piste évoquée : images qui sont chiffrées

**Comment by btrd** [comment]
En attente de réponse sur mattermost

**Comment by btrd** [comment]
@Grainedepaillette ça devrait être amélioré en staging, j'ai changé la façon dont l'on affiche les photos de profil des utilisateurs et administrateurs

**Comment by mch2608** [comment]
C'est amélioré en staging, possible de faire l'opération aussi en prod ? on y rencontre encore de la prod

**Comment by btrd** [comment]
C'est aussi en prod depuis la dernière mise en production.

**Comment by mch2608** [comment]
Après constat de lenteurs au niveau du vivier, je réouvre le ticket

**Comment by jrmlnzz** [comment]
@sebastiencarceles si tu te plonges dans du refacto ce sera peut-être l'occasion si tu veux creuser davantage le code ?

**Comment by sebastiencarceles** [comment]
Je note ici les optimisations et améliorations effectuées.

1/ Sur le vivier et dans les offres, le mécanisme qui permettait de sélectionner tout visait à désérialiser toutes les entrées de la base pour mettre des checkbox cachées dans la page, ce qui pouvait occasionner des lenteurs. Ça a été supprimé sur #1277, ce qui a pu contribuer à améliorer les performances de ces deux pages.

2/ D'après Sentry, les requêtes lentes sur le vivier se produisent essentiellement sur les instances `dga` et `anssi`, et beaucoup moins sur `cvd`. J'ai donc harmonisé les productions sur scalingo pour avoir la même puissance et la même quantité de containers.

3/ Toujours d'après Sentry, les requêtes lentes du vivier sont systématiquement sur des recherches. Par exemple : https://contractuels.civils.defense.gouv.fr/admin/candidats?s=sebastien
Et effectivement, c'est très reproductible, on a facilement des temps de réponse de l'ordre de 5 à 8s.
On voit que 99% du temps passé vient de la recherche elle-même, opérée par `pg_search` au niveau de la base de données. Les metrics de celle-ci indiquent pourtant qu'elle est loin d'être surchargée (CPU très bas, mémoire à 50%).

J'ai fait une petite optimisation (#1315) qui a permis de réduire par 2 le temps d'exécution de la recherche, passant de environt 7s à 3.5s :
![image](https://user-images.githubusercontent.com/1193334/177299712-988d881b-f2b1-408f-90bc-64806971a1e8.png)

Toutefois je ne trouve pas d'autre moyen simple d'optimiser cette recherche. Si on souhaite aller plus loin, je propose de réfléchir à abandonner `pg_search` pour adopter à la place un outil de recherche dédié, comme Elasticsearch.

@jrmlnzz est-ce que tu penses qu'il faut aller plus loin ?

**Comment by jrmlnzz** [comment]
Merci pour tout ce que tu as fait Sébastien ! Je pense que c'est très bien comme ça, on va rester sur `pg_search` pour l'instant. C'est déjà nickel d'avoir divisé le temps par 2 !
