### ISSUE TITLE
Back / Offres : les comptes employeurs notifiés en GE/ES/RH sur une offre disposent des droits d'un employeur sur l'offre

### ISSUE THREAD

**Issue by mch2608** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1020]
Règles : il est possible de notifier un compte employeur (inscrit sur l'outil par le responsable fonctionnel) à un rôle différent du rôle employeur sur une offre. Le compte doit avoir des droits limités au rôle pour lequel il a été notifié. 

Test réalisé en pré-prod et en prod 

Comportements constatés : Les comptes employeurs notifiés en tant que GE / ES / RH sur une offre d'emploi ont les mêmes droits que les employeurs de l'offre. Ils peuvent modifier l'offre, gérer les candidatures etc... 

Comportements souhaités : Les comptes employeurs notifiés en tant que GE, ES, RH sur une offre d'emploi ont, sur l'offre d'emploi,  uniquement les droits d'actions associés au rôle pour lequel ils ont été notifié. 

Situation qui se présente occasionnellement. 
Voir le temps de développement nécessaire.

**Comment by btrd** [comment]
Ça demande une refonte de la gestion des droits, je dirais minimum 3 jours. Plus du temps pour que vous testiez la nouvelle gestion des droits.

**Comment by Grainedepaillette** [comment]
@btrd Merci pour l'estimation. Ce cas étant relativement minime pour le moment : la plupart des administrateurs ayant un rôle employeur à l'origine sont taggués dans le champ employeur sur une offre d'emploi, on ne prendra pas en compte dans les prochains sprints. 

Néanmoins, ticket à garder en tête, car il l'avenir, il serait bien d'améliorer la confidentialité sur ce point.
