### ISSUE TITLE
Back / Courriel : Pouvoir intégrer du lien URL dans les textes

### ISSUE THREAD

**Issue by mch2608** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1080]
Comportement constaté : lorsqu'un lien URL est saisi dans un courriel de la messagerie embarquée, le lien est cliquable pour le candidat sur sa boîte personnelle. En revanche, le lien n'est pas cliquable sur sa messagerie CVD. 

Comportement souhaité : 
- lorsqu'un lien URL est saisi dans un courriel de la messagerie embarquée, le lien est cliquable pour le candidat à la fois sur sa boîte personnelle et à la fois sur sa messagerie CVD. 
- Donner la possibilité aux utilisateurs d'inscrire de l'hypertexte (insérer un lien sous le texte)

**Comment by jrmlnzz** [comment]
<img width="819" alt="Capture d’écran 2022-08-08 à 14 27 54" src="https://user-images.githubusercontent.com/88372553/183417833-e206f358-d12b-4729-992a-937ce55f4957.png">

**Comment by jrmlnzz** [comment]
@sebastiencarceles je te laisse la demande en l'état. Juste pour t'apporter des précisons, le screenshot ci-dessus c'est la vue que tu as quand tu vas dans ton espace candidat -> mes candidatures -> mes échanges, et effectivement le lien n'est pas cliquable.

**Comment by jrmlnzz** [comment]
Il y a plusieurs demandes dans ce ticket, tu préfères qu'on le divise ou c'est bon pour toi de travailler ces deux points en parallèle ?

**Comment by sebastiencarceles** [comment]
@jrmlnzz Je veux bien qu'on fasse un nouveau ticket pour ce point stp : 

> Donner la possibilité aux utilisateurs d'inscrire de l'hypertexte (insérer un lien sous le texte)

Car si on parle de mettre un éditeur riche ici : 
![image](https://user-images.githubusercontent.com/1193334/183590297-16d1e62b-24bb-44f6-a26f-6738e0f42e9c.png)

Alors c'est pas mal de travail ! Parlons-en dans un ticket dédié, ce sera plus clair.
