### ISSUE TITLE
Error tracking: remplacer Rollbar par Sentry

### ISSUE THREAD

**Issue by sebastiencarceles** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1269]
Comme le compte Rollbar actuel est lié à une entreprise disparue (Novelis), il faut créer un nouveau compte. L'usage chez Beta Gouv est plutôt d'utiliser Sentry. On remplace donc Rollbar par Sentry.

**Comment by Queenze972** [comment]
@sebastiencarceles peut-on clore ce ticket ?
