### ISSUE TITLE
Mettre à jour la version de Rails pour fixer la vulnérabilité XSS

### ISSUE THREAD

**Issue by sebastiencarceles** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1273]
Voir : 

https://github.com/betagouv/civilsdeladefense/security/dependabot/38 

https://github.com/betagouv/civilsdeladefense/security/dependabot/37

**Comment by Queenze972** [comment]
@sebastiencarceles peut-on clore ce ticket ?
