### ISSUE TITLE
Multidiffusion: Indeed

### ISSUE THREAD

**Issue by sebastiencarceles** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1283]
Il existe une API pour poster des jobs directement sur Indeed : https://developer.indeed.com/docs/indeed-apply/

**Comment by Queenze972** [comment]
@sebastiencarceles peux-tu me confirmer qu'aucun développement pour diffusion automatique des offres du SI E-recrutement jusqu'à INDEED n'a été entrepris ? Certaines offres enregistrées dans E-recrutement (ou peut-être un autre site defense.gouv.fr) sont visibles sur Indeed. 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/8d88bdd9-3dcf-4242-b427-7b96ed8ac4e2)

**Comment by sebastiencarceles** [comment]
@Queenze972 je te confirme qu'on n'a fait aucun développement en ce sens.

**Comment by Queenze972** [comment]
@sebastiencarceles  Merci de ton retour. 
Pour ton information, il s'agit en faite d'une fonctionnalité côté INDEED qui scanne tous les sites de recrutement et remonte, dans INDEED, les offres d'emploi accessibles sans authentification (comme Linkedin).
