### ISSUE TITLE
Conformité DashLord

### ISSUE THREAD

**Issue by 0jerome** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1366]
Repo Git de DashLord : https://github.com/socialgouv/dashlord
DashLord de Civil de la Défense : https://dashlord.incubateur.net/url/civilsdeladefense-fabnum-fr/

Hello Sébastien, je me permets de te proposer un ticket global qui se divisera en plusieurs parties, mais qui regroupera les actions DashLord ainsi que la documentation (repo) consacré.

On a plusieurs points ciblés par le DashLord que nous devons coché, et certains qui ne sont pas entièrement de notre ressort.
Nous, il faudrait que l'on jette un oeil sur :
- Scripts tiers et cookie, je n'ai pas davantage d'informations. Est-ce que ça te parle ?
- Déclaration de mise en accessibilité : On nous dit ici que les éléments ne sont pas détectés pourtant, ils sont bien présents. On parle de mention "Accessibilité : non conforme" qui doit être présente sur chaque page, et elle y est, dans le footer. Ainsi que la déclaration en elle-même : qui est ici : https://contractuels.civils.defense.gouv.fr/pages/declaration-d-accessibilite. Est-ce que tu peux voir si le robot réussi bien à accéder à cette page ? Peut-être que le chemin n'est pas assez claire ?
Mentions légales et politique de confidentialité, il semblerait que des mots précis ne soit pas identifiés, je te propose de réécrire ces phrases pour les inclure, selon le modèle de Bêta.

**Comment by Queenze972** [comment]
@sebastiencarceles peut-on clore ce ticket ?
