### ISSUE TITLE
BO : changement statut d'un candidat

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1424]
**Ce que je fais** 
Sur le BO en prod et en préprod, aller sur l'onglet Vivier puis sélectionner un candidat, le mettre au statut de Retenu.e et essayer de le passer en Rédaction contrat. Le statut ne change pas.

**Ce qu'il se passe**
Il est impossible d'avoir le statut Rédaction contrat avec n'importe quel autre statut en amont. 

**Ce qu'il devrait se passer**
Le statut change en Rédaction contrat 

**Fréquence**
Le bug apparait tout le temps

![CVD Tests - statut](https://user-images.githubusercontent.com/115472577/203970293-7a87bcce-db62-4be1-b9ce-0c6e4131aa7a.png)

**Comment by sebastiencarceles** [comment]
Hello @SophieLarroumet 

Je ne suis pas sûr qu'on ait une erreur technique ici. C'est plutôt un cas fonctionnel : 

![image](https://user-images.githubusercontent.com/1193334/224474915-26e84978-b0d9-4eaf-803f-d6b52a196202.png)

Qu'en penses-tu ?

**Comment by SophieLarroumet** [comment]
Bonjour Sébastien, 

Je suis d'accord avec toi, je vais communiqué aux intrapreneurs (lors de mes tests je n'avais pas vu les messages en bas à droite). 
J'ai testé à nouveau et je n'ai pas eu de difficulté. 

Je cloture ce ticket
