### ISSUE TITLE
[DGA] CV illisibles 

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1444]
**Ce que je fais :** 
Lorsque je me connecte sur l'environnement de la DGA et que je me dirige sur la fiche candidat de la dernière offre DGA publiée : 
![DGA-Bug-CV Illisible](https://user-images.githubusercontent.com/115472577/217005486-c3ad841d-aeb2-44b3-895f-9b00e471b6b2.jpg)

La page s'ouvre lorsque je clique sur « DOCUMENTS » télécharger le CV :
![DGA-Bug-CV Illisible 2](https://user-images.githubusercontent.com/115472577/217005519-ffc0f1ff-35b4-4263-b964-6d686f280683.jpg)

**Ce qui devrait se passer** 
Normalement je peux voir le CV directement sur la page du candidat et je devrais pouvoir télécharger le CV

**Fréquence :** 
Idem sur le candidat d’après. 
On retrouve le problème sur toutes les autres offres.

**Comment by sebastiencarceles** [comment]
On a vu que ça concernait les CV sur une période de quelques jours. Est-ce que ce que ce ticket est encore pertinent ou bien on peut le clôturer ?
