### ISSUE TITLE
Impossible de publier une offre - Env staging

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1468]
**Ce que je fais :** 
Lorsque je remplie le formulaire de création d'une offre le bouton publier n'existe plus. Je clique donc sur enregistrer et lorsque je suis dans le Back-Office Onglet Offre et que je clique sur les ... puis sur publier il ne se passe rien. 

https://www.loom.com/share/b9146309b3df4d6593cb88d0439a8d0f 

**Fréquence :**
Tout le temps

**Comment by SophieLarroumet** [comment]
Hello @sebastiencarceles,
Comme c'est sur l'environnement staging je supprime ce ticket ?

**Comment by SophieLarroumet** [comment]
Non il n'existe pas, du moins je n'ai eu aucun retour.

**Comment by sebastiencarceles** [comment]
Bonjour @SophieLarroumet 

J'ai du mal à comprendre sur quelle instance de staging tu reproduis ce bug. Dans le loom il y a écrit SGDSN mais je ne vois pas ton compte admin sur cette instance https://erecrutement-sgdsn-staging.osc-fr1.scalingo.io. 
Quel compte utilises-tu ? Sur quelle instance ?

Merci

**Comment by sebastiencarceles** [comment]
Ah mais ok je viens de comprendre en fait : il y a un paramètre pour imposer un délai entre la création de l'annonce et sa publication.

![image](https://github.com/betagouv/civilsdeladefense/assets/1193334/a9950bbe-14c1-4378-9149-319e0ef0a033)

Si ce délai est à 0, alors tu peux publier l'annonce immédiatement. Sinon, il faut créer l'annonce puis attendre le nombre de jours indiqués.
