### ISSUE TITLE
Notifications journalières ne sont pas reçues - Uniquement DGA

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1474]
**Ce qui se passe :** 
Comme indiqué dans le ticket : https://github.com/betagouv/civilsdeladefense/issues/1408
La DGA ne reçoit pas le récapitulatif journalier sur les boîtes mail des utilisateurs (tous les rôles sont concernés). Contrairement aux autres entités. 

Remember : lorsque le bug des mails avaient été corrigés tout était revenu à la norme sauf pour la DGA. Est-ce qu'il y a un lien ?

**Comment by SophieLarroumet** [comment]
Hello Sébastien, 

La DGA a reçu deux notification le 28 mars depuis l'activation de la plateforme. Les personnes ayant reçues les notifications sont madame Schneck et madame Bret.
Et depuis elles n'ont rien reçes.

**Comment by sebastiencarceles** [comment]
Suite à mon fix et au tracking que j'ai mis en place, je suis à peu près sûr que ces deux personnes ont bien reçu les emails ces derniers jours. Je t'invite  à vérifier auprès d'elles et à passer le ticket à Done le cas échéant. Merci

**Comment by SophieLarroumet** [comment]
J'ai eu un retour de la DGA, ils reçoivent bien les notifications.
