### ISSUE TITLE
Anssi - Formulaire de candidature - Impossible de renseigner langue

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1484]
**Ce que je fais :** 
Sur l'environnement de production de l'ANSSI dans le formulaire de candidature, il est impossible de renseigner la langue contrairement sur l'environnement de la DGA ou le SGA 
https://www.loom.com/share/380368bda0674c948d5b78ab9a9411f7

**Fréquence :** 
Alerte remontée le 14/04

**Comment by sebastiencarceles** [comment]
Bonjour @SophieLarroumet 

Les langues étrangères sont des données dynamiques, paramétrées dans le back office. Il faut donc qu'un compte admin avec les droits suffisants : 
1. aille dans Paramètres
2. ouvre les Langues étrangères
3. renseigne une ou des langues étrangères

![image](https://user-images.githubusercontent.com/1193334/233775458-42214523-5168-4ec1-b891-d35f13f1c9c8.png)

**Comment by SophieLarroumet** [comment]
Info communiquée à l'ANSSI.
Je cloture le ticket
