### ISSUE TITLE
Cartouche des offres - "..." ne marche pas

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1504]
**Environnement :**
Prod SGA : https://contractuels.civils.defense.gouv.fr/
Préprod : https://civilsdeladefense-staging.fabnum.fr/admin/offresdemploi

**Ce que je fais :** 
Lorsque l'on clique sur le bouton "…" à partir de la page principale de l'onglet "Offres" et que l'on sélectionne la valeur "Pubier" alors l'action est bien prise en compte et l'offre est publiée (cf. message annonce mise à jour) en revanche, lorsque l'on revient sur cette même offre et que l'on souhaite réaliser une 2ème action à partir du même bouton ALORS, c'est KO. Le détail du bouton "..." n'apparaît pas.  

Exemple lorsque je passe d'une offre archivée à une offre publiée : 
https://www.loom.com/share/8aa0ef7913f94e158a1063bacacb27a0

Exemple lorsque je passe d'une offre publiée à archivée :
https://www.loom.com/share/6e77280dd94047228a6b7dc9bbbcda43

Il est nécessaire 1) de rafraîchir la page ou 2) de cliquer sur la cartouche de l'offre (nouvelle page) à partir de laquelle on voit apparaître le détail de l'offre pour pouvoir effectivement accéder à nouveau à ce bouton "..." et accéder au menu déroulant.
Ce comportement est valable lorsque l'on sélectionne les valeurs : Publier ; archiver. 
La sélection de la valeur "Transférer" ne pose pas de PB (car la page est rafraîchit, cf. chargement d'une nouvelle page). Le PB doit donc être lié au rafrahcissement car pour les autres valeurs, la modification du stats, n'implique pas un changement de page. 

**Fréquence :** 
Tout le temps

**Comment by sebastiencarceles** [comment]
Hello @SophieLarroumet , ce ticket t'es affecté, c'est parce qu'il te reste quelque chose à faire dessus ? Est-ce que je peux le prendre ?
Merci
