### ISSUE TITLE
Cases à cocher "Tout sélectionner" et "Sélectionner la page"

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1505]
**Environnement :**
Prod SGA : https://contractuels.civils.defense.gouv.fr/
Préprod : https://civilsdeladefense-staging.fabnum.fr/admin/offresdemploi

**Ce que je fais :** 
Lorsque l'on utilise les cases à cocher sur une page donnée, RAS. En revanche, en tant qu'utilisateur, on s'attend à ce que lorsque l'on parcourt les pages offres (exemple : passage de la page offre 1 à la page 2) ALORS, la sélection réalisée doit être maintenue. 
Actuellement, quand l'utilisateur clique sur "Tout sélectionner" (soit toutes les offres actives (afin de mener une action), l'action n'est pas enregistrée si l'on change de page. De la même façon pour la case "Sélectionner la page". 

https://www.loom.com/share/8192f500b7954b8dbfad6287bd429772

**Fréquence :** 
Tout le temps

**Comment by sebastiencarceles** [comment]
Hello @SophieLarroumet 

> en tant qu'utilisateur, on s'attend à ce que lorsque l'on parcourt les pages offres (exemple : passage de la page offre 1 à la page 2) ALORS, la sélection réalisée doit être maintenue.

J'ai l'impression que cette demande est un anti pattern. En effet, pour tous les logiciels en ligne qui proposent une pagination avec des éléments à cocher (individuels, page, tout), **le changement de page annule la sélection**.

Quelques exemples :
- Gmail : https://www.loom.com/share/d2b40303089444a58b3182b97ffe990f
- GitHub : https://www.loom.com/share/d74b367e342f4724bc753f3b0e829f39
- Sentry : https://www.loom.com/share/fe1235c2f12b46938c4cdffb908f751c

On peut en trouver de nombreux autres, et peut être aussi des contre exemples, mais je pense que l'UX implémentée dans CVD à ce sujet est conforme à la convention / l'usage habituel. Donc je ne recommande pas d'effectuer ce changement. 

Qu'en penses-tu ?

**Comment by sebastiencarceles** [comment]
@Queenze972 Que penses-tu de mon explication ? À mon avis il faut laisser comme c'est actuellement.

**Comment by Queenze972** [comment]
@sebastiencarceles OK sur l'explication, c'est mon avis aussi. Je clôture le ticket.
