### ISSUE TITLE
Carte Candidat - Site Web

### ISSUE THREAD

**Issue by SophieLarroumet** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1517]
**Environnement** 
Prod SGA 
Preprod

**Ce que je fais** 
Lorsque le recruteur renseigne un site web, il n'est pas enregistré automatiquement par le SI il faut qu'il tape sur la touche entrée. 
https://www.loom.com/share/8aa1c70923b44bfeaa086e6cc1ef21cc

**Comment by sebastiencarceles** [comment]
Hello @SophieLarroumet , je t'invite à tester le correctif sur https://erecrutement-cvd-staging-pr1559.osc-fr1.scalingo.io/admin/offresdemploi/responsable-achat-d-infrastructures-f-h/candidatures/a11dec67-9d87-44fb-8dac-b5ac9025b95a
