### ISSUE TITLE
Reconstruire le déploiement automatique sur Scalingo

### ISSUE THREAD

**Issue by sebastiencarceles** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1609]

**Comment by sebastiencarceles** [comment]
Bonsoir @Queenze972 

Je travaille sur le déploiement des applications sur Scalingo depuis le nouveau GitHub. 

Pour cela, il faut que je relie chaque application au nouveau dépôt, mais comme je ne suis pas owner de l'organisation Bureau-Systeme-d-Information-BSI, je ne peux pas lister ses dépôts dans Scalingo :

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/c282b7e7-b2a3-4faa-9e8a-1f6eaa4ecf3f)

Peux-tu me mettre owner de l'organisation, même temporairement, le temps que je configure le déploiement des applications sur Scalingo ?

Alternativement, tu peux faire la configuration sur Scalingo depuis ton compte. Dans ce cas, je te donnerais les infos dont tu auras besoin. Je vais déjà t'inviter aux apps sur Scalingo, pour qu'on soit plusieurs a avoir les accès.

Merci

**Comment by Queenze972** [comment]
Bonjour @sebastiencarceles , c'est fait ! Tu as désormais le rôle "Owner" de l'organisation BSI. Aucun problème de notre côté à te laisser ce rôle, seul ce projet au BSI est présent sur GitHub.

**Comment by Queenze972** [comment]
@sebastiencarceles, je me suis bien authentifiée sur la plateforme SCALINGO via les invitations envoyées hier. J'ai bien accès aux environnements PREPROD des différentes AU mais je ne suis pas autorisée à accéder aux environnements PROD : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/a49555cb-6d47-4dbc-8031-3e6c503ab665)

Ci dessous le message d'erreur affiché lorsque je clique pour rejoindre une invitation SCALINGO d'un ENV de PROD : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/bbb28b39-c6d9-4d15-afc7-946bab3e8215)

**Comment by sebastiencarceles** [comment]
Oui @Queenze972  j'ai rencontré le même problème vendredi. Je te propose de contacter le support, via le chat ou par email (support@scalingo.com), ils vont te donner accès à cette région (et donc aux applications de prod).

**Comment by sebastiencarceles** [comment]
Pour info j'ai rencontré un nouveau problème : bien que je sois owner de l'organisation, celle-ci n'apparaît pas sur le panneau de configuration de Scalingo. J'ai contacté le support pour essayer d'en savoir plus.

**Comment by sebastiencarceles** [comment]
Pour info @Queenze972 tout est OK, j'ai pu reconstruire le déploiement automatique des instances de prod, préprod et review apps.

**Comment by Queenze972** [comment]
@sebastiencarceles peut-on clore ce ticket ?
