### ISSUE TITLE
Redéployer les review apps des PR réalisées et solliciter Elise pour la recette

### ISSUE THREAD

**Issue by sebastiencarceles** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1611]

**Comment by sebastiencarceles** [comment]
C'est bon @Queenze972 j'ai redéployé les review apps pour toutes les PR ouvertes. Tu peux donc les tester. Cela concerne : 

#1545
#1552 
#1553
#1554
#1559
#1568
#1576 

Pour chacune, j'ai rappelé dans la Description de la PR le sujet, et le lien vers le ticket d'origine (l'issue).

Et pour chacune, tu peux ouvrir la review app en dépliant les Checks, et en cliquant sur "Details" en face de la ligne "deploy/sclngo" : 



![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/0818edd0-5cd0-4067-8574-d04b827040a3)


Normalement les logins / passwords sont les mêmes que précédemment, mais je ne sais pas si tu les as à ta disposition, n'hésite pas à revenir vers moi si besoin.

Merci

**Comment by Queenze972** [comment]
Bonjour @sebastiencarceles ! Super nouvelle. Du coup je dois tester la PREPROD entièrement et les tickets mentionnés dans ton commentaire ?

**Comment by sebastiencarceles** [comment]
Oui tout à fait.

Pour tester entièrement la preprod, tu peux utiliser une des instances de staging, par exemple **erecrutement-cvd-staging** : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/8cdfac5c-7691-4562-8c4f-1ad0d59947f0)

Et pour tester les 7 tickets liés plus haut, chacun possède sa propre review app, comme discuté précédemment.

**Comment by Queenze972** [comment]
Parfait, merci pour les infos. Je te fais un retour complet dès que possible !

**Comment by sebastiencarceles** [comment]
Top, merci :pray: 

N'hésite pas à faire tes retours directement dans les tickets concernés.

**Comment by Queenze972** [comment]
@sebastiencarceles peut-on clore ce ticket ?
