### ISSUE TITLE
Non affichage des images (HP)

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1619]
ENVIRONNEMENT : PREPROD, STAGING

**[Home-Page]** 
Sur la page d'accueil, les images ne sont pas affichées : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/824b4f9d-9874-457b-bb56-32bdc35f9326)

Criticité : Non bloquant

**Comment by sebastiencarceles** [comment]
Bonne nouvelle @Queenze972 , cette image est paramétrable ici : 



![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/8d098a73-4cd8-45ec-b7d9-9c8ee253469a)

L'image s'affiche ensuite : 



![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/e87c456b-39c1-47a7-812b-8ea21c18a919)

Le logo opérateur est lui aussi paramétrable.
