### ISSUE TITLE
[PROD] [FO > Candidature spontanée] Page 500 ERROR quand aucune offre est tagguée "CS"

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1631]
Environnement : PROD 
Page : FO > Candidature spontanée

**Comportement actuel :** Lorsqu'un candidat clique sur "Candidature spontanée", il est renvoyé vers une page 500 ERROR car aucune offre n'est référencée comme "Candidature Spontanée" (= case cochée dans le formulaire d'ajout d'une offre). 

**Comportement attendu :** 
#CAS d'USAGE n°1# 
Si une offre est référencée comme "Candidature spontanée", alors c'est cette offre qui est affichée lorsque le candidat clique sur le lien. 

#CAS d'USAGE n°2#
Si aucune offre est référencée comme "Candidature spontanée", alors un message applicatif s'affiche sur la page sous ce format là (respect de la charte graphique de l’État) : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/711607ea-1f3a-4a38-a2c0-66923d9317d1)
Avec le message suivant "Aucune candidature spontanée n'est disponible pour le moment. Parcourez les offres d'emplois disponibles et ajoutez dans vos favoris celles qui vous intéressent". 
Le bouton "Voir les offres" renvoie à la page "Nos offres".

**Comment by Queenze972** [comment]
Proposition Sébastien : Si aucune offre Candidature spontanée n'est paramétrée alors le lien "Candidature spontanée" ne s'affiche pas. 
OK pour moi cette solution.

**Comment by sebastiencarceles** [comment]
@Queenze972 alors j'ai vérifié, on a bien ce comportement là qui est implémenté : 

> Si aucune offre Candidature spontanée n'est paramétrée alors le lien "Candidature spontanée" ne s'affiche pas.

J'ai regardé sur chaque instance de prod et je n'arrive pas à constater l'erreur 500 décrite.

- DGA : pas d'offre CS donc pas de lien
- ANSSI : une offre => le lien fonctionne bien, pas d'erreur
- CVD : une offre => le lien débouche sur une 404

En effet l'offre tagguée CS est en brouillon et non publiée. 

Je vais faire une PR avec une proposition de solution : le lien "Candidature spontanée" devrait être visible que s'il y a une offre CS **publiée**. Est-ce que c'est ok pour toi ?

**Comment by Queenze972** [comment]
@sebastiencarceles Parfait, c'est bien noté pour la RG.
