### ISSUE TITLE
[FO > Tuile OE] Modification du design d'une tuile OE

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1638]
Comportement actuel : 
Actuellement, une tuile offre se présente de la façon suivante : 

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/1da2d0da-1470-4f9e-b9a0-d09e4adc17af)

Comportement attendu : 
- Mentionner la durée du contrat pour les CDD et les Job étudiant 
Dès lors que l'OE est (type de contrat= CDD et JOB ETUDIANT) alors la durée du contrat s'affiche dans la tuile OE. 
Si aucune valeur est sélectionnée côté BO dans le champ "Durée du contrat" alors rien ne s'affiche sur le tuile OE côté FO. 
- Ajout d'un icône "contrat" devant la mention du contrat 
- Ajout d'un icône "localisation" devant la localisation 
- Renseigner le domaine professionnel sous la forme du tag gris comme sur la maquette

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/4d4e7702-6290-432e-ad12-6a042d17ea1a)

NB : La nouvelle fonctionnalité "Ajouter aux favoris" sera traitée dans un ticket différent #1639

**Comment by sebastiencarceles** [comment]
Attention pas d'icône en fait sur le tag du domaine d'activité
