### ISSUE TITLE
[FO > Détail d'une OE] Modification du design détail OE

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1640]
**Comportement actuel :** 
Actuellement, le détail d'une OE se présente comme ci dessous : 
![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/2175418b-de0f-4158-a777-89ac86c19d52)

Comportement attendu : 
Il s'agirait d'opérer les modifications suivantes : 
- Suppression du logo "Imprimer" 
- Ajout de la fonction "Ajouter aux favoris" (cf. ticket #1639 )
- Ajout du lien "Télécharger en PDF" avec icône DSFR 
Si le candidat clique sur le lien "Télécharger le PDF", alors l'offre se télécharge via le navigateur web. Le modèle de l'offre correspondant au modèle utilisé actuellement par la fonction "Imprimer".

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/65347dbb-7521-4c97-9fb2-0069ca62dff3)

**Comment by Queenze972** [comment]
[Offre d'emploi Administrateur adjoint sécurité systèmes F_H Crozon, 29, Finistère, Bretagne - Civils de la Défense.pdf](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/files/14696575/Offre.d.emploi.Administrateur.adjoint.securite.systemes.F_H.Crozon.29.Finistere.Bretagne.-.Civils.de.la.Defense.pdf)

**Comment by sebastiencarceles** [comment]
Note : ce ticket est traité avec d'autres, connexes, dans #1699
