### ISSUE TITLE
[FO > Formulaire de création d'un compte candidat] Modification du formulaire

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1659]
FO > Modification du formulaire de création d'un compte candidat 

**Comportement actuel :** 
Actuellement, le formulaire de création d'un compte candidat comporte plusieurs champs et se présente sous la forme suivante : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/692a6429-93f8-4932-8fa7-545be6119f8d)
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/aa8c0c77-f3c0-4040-9a83-0c0b2c7735f1)

**Comportement attendu :**
1. Modification du champ "Mot de passe" pour un champ du même type que ci dessous : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/865bc5f6-c746-4ff1-80cc-baa1dbb4685d)
=> Ajouter les pré-requis (tels que l'image jointe) en dessous des deux champs à saisie libre :
- 8 caractères minimum
- 1 chiffre
- 1 lettre minuscule minimum
- 1 lettre majuscule minimum
- 1 caractère spécial minimum

=> Notifier à l'utilisateur quels sont le ou les caractères manquants pour que l'utilisateur en soit informé au cours de la saisie de son mdp.
=> valable uniquement pour le champ "Nouveau mot de passe".
- S'il saisit un premier caractère 'une majuscule" dans le champ "Mot de passe" alors le texte "1 lettre majuscule minimum" devient vert et la croix rouge à gauche est transformée en "v" vert.
-S'il supprime un des caractères requis dans la saisie du mdp, le texte redevient rouge et à gauche une croix.

=> Ajouter un icône "œil" (comme l'image) dans les champs "Mot de passe" et "Confirmation mot de passe" permettant à l'utilisateur de visualiser le mdp saisit.
- Si l'utilisateur clique sur l'icône dans un des champs alors l'icône œil est barré et le mdp est visible en toutes lettres. 

2. Suppression du champ "Poste actuel" 

3. Ajout d'un *, à la fin des phrases, pour mentionner le caractère obligatoire des deux dernières cases à cocher : "En soumettant ce formulaire, ..." + "Je certifie être majeur(e) et disposer de mes droits civiques".

**Comment by sebastiencarceles** [comment]
@Queenze972 j'ai une question ici stp : est-ce qu'on enlève le "poste actuel" de **ce formulaire uniquement**, ou bien de **toute l'application ?**

**Comment by Queenze972** [comment]
@sebastiencarceles Pour le moment, on supprime cette info de ce formulaire de création de compte. 
On ne le supprime pas de toute l'application, je n'ai pas encore mesuré les impacts : cette info est un peu de partout dans l'application. Merci.

**Comment by sebastiencarceles** [comment]
Bien noté, merci
