### ISSUE TITLE
[ANO > Référentiel Expériences] Suppression impossible d'un item 

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1666]
**Comportement actuel :** En tant qu'utilisateur BANT, quand j'essaye de supprimer un item du référentiel "Expériences", en dessous de l'item "CANDIDATURE spontanée", un message d'erreur en anglais apparait : _"Translation missing : fr.admin.settings experience_levels.destroy.failure.foreign_key_violation"._ La valeur ne se supprime pas. 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/0da72643-4bd0-49b7-a147-a3df07b96ea0)

**Comportement attendu :** L'item doit se supprimer sans problème au clic sur la poubelle en fin de ligne.

**Comment by Queenze972** [comment]
@sebastiencarceles Ce bug empêche le bureau métier de mettre à jour les référentiels en PROD. Aurais-tu le temps de regarder cela ? Merci d'avance.

**Comment by sebastiencarceles** [comment]
@Queenze972 je travaille dessus mais je n'arrive pas à reproduire le bug, que ce soit en local ou sur une instance de staging : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/ce01bbfb-16d9-4840-baae-73739cf4ebb8)

Je suppose que c'est une question de données. Est-ce que je peux faire le test sur la prod ? De quelle instance s'agit-il ? Je peux essayer de supprimer le **0 à 1 an** qu'on voit sur ta capture ?

**Comment by sebastiencarceles** [comment]
Ah non c'est bon j'ai trouvé ! Je prépare un fix .
