### ISSUE TITLE
[Sécurité] Analyse robustesse des mots de passe

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1667]
Comme discuté par mail (échanges du 8/3) , nous aimerions avoir un audit/une analyse sur la robustesse des mots de passes sur l'application. 

- Nombre de caractères demandés suffisants 
- Typologie des caractères demandés 
- Différence avec les utilisateurs ADMIN ?

Merci.

**Comment by sebastiencarceles** [comment]
@Queenze972 les règles pour les mots de passe sont les mêmes pour les users et pour les admins.

# Situation actuelle

Les règles sont les suivantes : 
- 8 caractères au moins
- 70 caractères au plus
- au moins un chiffre
- au moins une minuscule
- au moins une majuscule
- au moins un caractère spécial parmi la liste suivante : `#?!@$%^&*-`

Le mot de passe n'est pas stocké tel quel en base. Il est d'abord chiffré et c'est ce chiffrement qui est stocké. Devise utilise [Bcrypt](https://github.com/bcrypt-ruby/bcrypt-ruby) pour le chiffrement, ce qui est [considéré comme sûr](https://www.freecodecamp.org/news/how-does-devise-keep-your-passwords-safe-d367f6e816eb/) et constitue un standard dans le monde des applications Ruby on Rails.

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/26d50b89-7c64-4605-81c6-7207bab0782c)

Par ailleurs, la base elle-même est chiffrée et n'est pas accessible par internet, seul le serveur y a accès : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/22392892-c927-4948-ac03-a306d59d33d7)

# Recommandations de la CNIL

Elle [recommande](https://www.cnil.fr/fr/questions-reponses-sur-la-nouvelle-recommandation-relative-aux-mots-de-passe-et-autres-secrets) de mettre en oeuvre une double authentification, OU BIEN de respecter les bonnes pratiques pour l'authentification par mot de passe simple.

Elle ne **recommande pas** de renouveler régulièrement les mots de passes.

Toutefois, la CNIL recommande de [définir un niveau minimal générique de 80 bits d'entropie](https://www.cnil.fr/fr/mots-de-passe-une-nouvelle-recommandation-pour-maitriser-sa-securite) (à comprendre comme un score de sécurité du mot de passe). Avec nos règles actuelles, et [d'après le calculateur](https://www.cnil.fr/fr/verifier-sa-politique-de-mots-de-passe), nous sommes à 53 bits d'entropie.

Pour atteindre 80, nous pouvons changer nos règles pour correspondre à l'exemple 1, qui est conforme aux préconisations : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/90923e68-f59c-4ca2-ba84-851f89fed912)

Les changements pour nous seraient donc les suivants : 
- passer à 12 caractères minimum
- élargir la liste de caractères spéciaux (pour atteindre 37 caractères spéciaux différents disponibles)

Une alternative (exemple 2 de la CNIL) serait de passer à 14 caractères minimum sans caractère spécial obligatoire : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/490ba3a6-7280-42f4-ab76-b01f7526c1c6)

Enfin, une autre possibilité proposée par la CNIL serait de rester avec une entropie minimum de 50, mais d'ajouter des mécanismes de restriction supplémentaires : 

1. Temporisation d'accès au compte après plusieurs échecs ;
2. Nombre maximal de tentatives autorisées dans un délai donné ;
3. "Captcha" ;
4. Blocage du compte après 10 échecs assorti d'un mécanisme de déblocage choisi en fonction des risques d'usurpation d'identité et d'attaque ciblé par déni de service.

Nous avons déjà le mécanisme 4 en place grâce à [Devise Lockable](https://www.rubydoc.info/github/heartcombo/devise/main/Devise/Models/Lockable) :

> Handles blocking a user access after a certain number of attempts (**10 tentatives dans notre cas**). Lockable accepts two different strategies to unlock a user after it’s blocked: email and time. The former will send an email to the user when the lock happens, containing a link to unlock its account. The second will unlock the user automatically after some configured time (**désactivé dans notre cas, c'est forcément par email**).

Nous pourrions facilement mettre en oeuvre le mécanisme 2 grâce à du rate limiting.

Donc au bilan, notre situation actuelle (règles qui donnent une entropie de 53 et mécanisme de blocage) **est conforme aux recommandations de la CNIL** mais pourrait être améliorée, soit par : 
- la modification des règles de mot de passe
- la mise en oeuvre d'un nouveau mécanisme de restriction (en l'occurrence le mécanisme 2 : nombre maximal de tentatives autorisées dans un délai donné)

# Recommandations de l'ANSSI 

L'ANSSI a publié un [guide très exhaustif sur l'authentification](https://cyber.gouv.fr/publications/recommandations-relatives-lauthentification-multifacteur-et-aux-mots-de-passe). J'ai retenu que : 
- la première recommandation est l'authentification multifacteur ou une authentification forte
- nos règles sur la complexité des mots passe sont dans l'état de l'art, **sauf du point de vue de la longueur**

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/45e8efa1-642e-498d-ba35-11a85a8a2654)

Je n'ai pas étudié le guide en détail : j'ai l'impression que les recommandations convergent avec celles de la CNIL et j'arrive globalement aux mêmes conclusions. Est-ce que tu penses qu'il faut aller plus loin dans l'étude de ce guide et faire des propositions d'amélioration de l'application, au delà des mots de passe, en ce qui concerne l'authentification ?

**Comment by Queenze972** [comment]
@sebastiencarceles grand merci pour cette analyse claire et complète. 
Je propose cela aux responsables fonctionnels et reviens vers toi pour la mise en place. 

Je pencherai plus sur le scénario 1 : 
- Passer à 12 caractères minimum
- Elargir la liste des caractères spéciaux autorisés 

Si l'on modifie cette règle, qu'est ce qu'il se passe pour les utilisateurs déjà authentifiés avec 8 caractères ?

**Comment by sebastiencarceles** [comment]
> Si l'on modifie cette règle, qu'est ce qu'il se passe pour les utilisateurs déjà authentifiés avec 8 caractères ?

A priori rien, c'est du contrôle en front seulement au moment de l'inscription.

En revanche, si on veut les obliger à renouveler leurs mots de passe, c'est possible :
- on leur fait un mail pour les prévenir au préalable, c'est toujours mieux
- on invalide leurs mots de passe, ce qu'il les obligera à passer par la récupération de mot de passe

À ce moment, iels seront soumis·es aux nouvelles règles.

**Comment by Queenze972** [comment]
Merci pour ce complément Sébastien. 
Il ne me semble pas nécessaire de les obliger, s'ils ne sont pas bloqués c'est OK pour moi. 
Juste s'ils font "MDP oublié", ils devront configurer un mdp avec les nouvelles exigences ?

**Comment by sebastiencarceles** [comment]
> Juste s'ils font "MDP oublié", ils devront configurer un mdp avec les nouvelles exigences ?

Oui c'est tout à fait ça @Queenze972

**Comment by Queenze972** [comment]
OK Merci Sébastien. Je ferme ce ticket d'analyse et je vais recréer un nouveau ticket pour mentionner les modifications à effectuer.
