### ISSUE TITLE
[BO > Formulaire d'ajout d'une offre d'emploi > 1.2 Paramètres de l'offre] Modifications des champs

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1670]
[BO > Formulaire d'ajout d'une OE > Paramètres de l'offre] 

**Comportement actuel :** Actuellement, le module "1.2 Paramètres de l'offre" est configuré comme ci dessous : 
![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/d607171e-588d-48b8-8e6c-375994ff9813)

**Comportement attendu :** Nous souhaiterions modifier ce module comme sur la maquette ci dessous : 
![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/21c16114-d2e9-488e-b9c8-e3aeac82c5a2)

Ce qui implique : 
1. Modification du libellé "Début de contrat" par "Prise de fonctions souhaitée" => obligatoire (mention *) 
Impact : Modification du libellé côté FO

2. Modification des libellés "Référence PEP" par "Référence CSP" => obligatoire (mention *)
+Champ "Date de publication" => obligatoire (mention *)
 
4. Modification des libellés "Référence BNE" par "Référence MOBILIA" => obligatoire (mention *) 
+Champ "Date de publication" => obligatoire (mention *)
5. Ajout d'un nouveau champ  "Catégorie/Niveau de l'offre" => obligatoire (mention *) + liste déroulante paramétrable
Impact : Ajout d'un onglet "Catégorie/Niveau de l'offre" permettant d'ajouter, modifier, supprimer des valeurs à la liste déroulante. Exemple de valeurs : A, B, C, 1, 2, 3
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/2822fca9-c618-4847-8496-d400280a0ad4)

Seulement pour les utilisateurs BANT (Admin). 
![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/ac9253d9-bc0d-40fc-84ca-7b21e0bd06bc)

6. Ajout d'un champ calendrier non obligatoire "Date limite de candidature" 
Impact : Côté FO, dans le détail d'une OE, sur le menu latéral gauche ajout d'un champ normé "Date limite de candidature". Ce champ est ajouté à la suite du champ "Prise de fonctions souhaitée". Si ce champ n'est pas rempli côté BO, alors ce nouveau champ ne s'affiche pas.

RG : La date limite de candidature doit être strictement supérieure à la date du jour. (ajout message d'erreur si tel est le cas à l'enregistrement). 

NB : Attention aux messages d'erreur si les champs obligatoires ne sont pas remplis à l'enregistrement.

**Comment by sebastiencarceles** [comment]
@Queenze972 j'ai une question sur les champs qui deviennent obligatoires.

Lorsqu'un champ n'était pas obligatoire, et qu'il le devient, on ajoute une validation au niveau du modèle. C'est ce mécanisme qui permet de vérifier que le champ est rempli à l'enregistrement : s'il ne l'est pas, ça remonte une erreur, qu'on peut afficher à l'utilisateur.

Seulement, le champ devient obligatoire pour _tous_ les records, y compris les anciens, qui n'ont peut-être pas de valeur pour ce champ. Si c'est le cas, alors ils ne peuvent plus être enregistrés tant que la valeur n'est pas renseignée, même si l'enregistrement concerne un autre champ.

Prenons un exemple : on a une offre d'emploi qui n'a pas de date de publication pour sa référence BNE. On dit que, désormais, cette date est obligatoire. Alors cette offre d'emploi ne peut plus être modifiée tant qu'on ne renseigne pas la date de publication. 

Ça parait logique, au niveau du formulaire d'offre d'emploi, car l'erreur va s'afficher et renseigner l'utilisateur. Toutefois cette limitation s'applique aussi lorsque l'offre est dépubliée, archivée, qu'elle passe en brouillon, etc. Là, c'est moins lisible : l'utilisateur ne comprend pas quel est le rapport entre la dépublication, par exemple, et la date de publication de la référence BNE.

Pour répondre à ce problème, on fait généralement une migration de données, qui consiste à attribuer des valeurs aux champs nouvellement obligatoires. Pour chacun d'un, il faut donc une règle qui indique la valeur à attribuer. Par exemple, on peut dire que la date de publication de la référence BNE est la date de publication de l'offre ou, si elle n'existe pas, la date de création de l'offre. On peut aussi faire un calcul, par exemple date de création de l'offre + 10 jours.

Dans ce ticket, ce problème concerne : 
- la date de publication de la référence BNE / MOBILIA
- la date de publication de la référence PEP / CSP
- le nouveau champ Categorie/Niveau de l'offre
- le nouveau champ Date limite de candidature

Peux-tu m'indiquer pour chacun des champs concernés comment il faudrait les renseigner pour les records existants ?
Merci

**Comment by Queenze972** [comment]
@sebastiencarceles désolée de mon retour tardif à ce sujet. 
Voici les règles si les données sont nulles : 
- Date de publication de la référence BNE / MOBILIA : date de création de l'offre 
- Date de publication de la référence PEP/CSP : date de création de l'offre 
- Champ catégorie/niveau de l'offre : Niveau I (le + d'offres) 
- Date limite de candidature : date de création de l'offre + 6 mois 

Merci beaucoup :)

**Comment by sebastiencarceles** [comment]
@Queenze972 je me suis trompé pour le champ "date limite de candidature" : comme il n'est pas obligatoire, il n'est donc pas besoin de le remplir, on peut le laisser vide.

Est-ce que tu veux quand même que je le remplisse avec la date de création de l'offre + 6 mois, pour les offres existantes ? Ou bien je le laisse vide ?

**Comment by Queenze972** [comment]
@sebastiencarceles Non pas besoin de le remplir alors, on laisse le champ vide ! Merci.
