### ISSUE TITLE
[BO > Vivier > Sélection filtre] PAGE 500 ERROR

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1684]
Étapes pour reproduire le bug : 
1. Se connecter au BO en tant que BANT 
2. Aller dans l'onglet "Vivier"
3. Sélectionner un item dans un filtre (ex : Souhaits géo) 
4. PAGE 500 ERROR 

=> Tous les filtres de la page sont impactés par ce bug sauf le filtre de recherche en saisie libre.

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/c4c91059-f42f-438e-95f6-489006b6c2f0)

**Comment by sebastiencarceles** [comment]
@Queenze972 il s'agit du même bug ransack, corrigé dans #1677

**Comment by Queenze972** [comment]
@sebastiencarceles je m'en doutais mais n'étais pas sûre. Du coup, quand on mettra en prod le fix #1677 , ce bug sera aussi résolu ?

**Comment by sebastiencarceles** [comment]
Oui absolument !
