### ISSUE TITLE
[MAIL AUTOMATIQUE > Désactivation automatique d'un compte utilisateur] Modification du mail

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1694]
Suite à une remontée de la DGNUM, nous devons modifier certains contenus de mails automatiques. 

**Ancien mail :** 
Bonjour [francois.reptin@intradef.gouv.fr](mailto:francois.reptin@intradef.gouv.fr), 
Nous vous invitons à mettre à jour votre compte utilisateur sur le site Direction générale de l'armement. Sans mise à jour de celui-ci sous 330 jours, nous vous informons qu'il sera désactivé automatiquement. 
Cordialement, 
L'équipe Direction générale de l'armement 

**Nouvel e-mail :**
Bonjour Prénom NOM, 

Nous vous invitons à mettre à jour votre compte utilisateur sur le site « Lien hypertexte du site Autorité Utilisatrice ». 
Sans mise à jour de celui-ci sous 30 jours, votre compte sera désactivé automatiquement. 

Cordialement, 

L’équipe de recrutement de « Autorité Utilisatrice »

**Comment by sebastiencarceles** [comment]
@Queenze972 je ne suis pas sûr d'avoir bien compris ce qu'on souhaite avoir ici. 

```
Bonjour Prénom NOM,
=> c'est déjà ce qu'on a : on met Prénom NOM si on les connait, sinon on met l'adresse email

Nous vous invitons à mettre à jour votre compte utilisateur sur le site « Lien hypertexte du site Autorité Utilisatrice ».
=> de quoi s'agit-il ? est-ce qu'on veut avoir un lien dans le corps du mail ici ? Quelle est sa valeur ? Qui est Autorité Utilisatrice ?

Sans mise à jour de celui-ci sous 30 jours
=> actuellement on a déjà 30 jours sur les instances CVD et DGA, donc a priori pas de changement ici
, votre compte sera désactivé automatiquement.

Cordialement,

L’équipe de recrutement de « Autorité Utilisatrice »
=> actuellement on a L'équipe <%= @service_name %>, avec le nom du service qui peut changer. Est-ce qu'on veut avoir exactement "Autorité Utilisatrice" ?
```

Donc globalement j'ai du mal à comprendre ce que veux dire "Autorité Utilisatrice". Est-ce qu'on veut mettre ça textuellement dans le corps du mail, ou bien c'est une façon de dire "service name" ?

Si jamais c'est compliqué d'expliquer à l'écrit, convenons d'un moment pour échanger à l'oral là-dessus, ce sera peut être plus simple !

**Comment by Queenze972** [comment]
@sebastiencarceles 

Pour moi "Autorité Utilisatrice" = Direction Générale de l'Armement, l'ANSSI et Civils de la Défense. Est ce le même que "service name" ? C'était pour personnaliser les mails en fonction des clients. 

Pour moi "Lien hypertexte de l'AU" = https://contractuels.civils.defense.gouv.fr/ + https://talents.ssi.gouv.fr/ 
Cela permet à l'utilisateur de pouvoir aller sur le site directement via le corps du mail. 

Est ce plus clair pour toi ?

**Comment by sebastiencarceles** [comment]
OK compris ! 

Effectivement, "Autorité Utilisatrice" c'est ce que j'appelle "service_name" parce que c'est codé comme ça. Je vais tâcher d'adopter le bon vocabulaire.

Bien compris aussi pour le lien.

Merci
