### ISSUE TITLE
[MAIL AUTOMATIQUE > Confirmation compte (GE, ES, RH)

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1696]
-	**Confirmation compte (Grand Employeur, Employeur superviseur, RH) = générer quand on ajoute un courriel dans une offre d'emploi :** 
**Ancien mail :** 

Bienvenue sur « Autorité Utilisatrice » [mail@monmail.fr](mailto:mail@monmail.fr) 
Vous pouvez confirmer votre courriel en cliquant sur le bouton ci-dessous : 

*Bouton lien « Je confirme mon courriel »* 

Proposition nouvel e-mail : 

**Bonjour,** 

Vous avez notifié comme « Rôle » dans une offre d’emploi sur le site de recrutement [URL site en fonction de l’environnement]. Pour y accéder, veuillez confirmer votre compte en cliquant sur le lien suivant : 

*Bouton lien « Je confirme mon courriel »* 

Votre compte ne sera pas activé tant que toutes les étapes de création de votre compte ou de confirmation de votre compte ne seront pas finalisées dans l’application. 

L’équipe de recrutement de « Autorité Utilisatrice »

**Comment by sebastiencarceles** [comment]
@Queenze972 j'ai plusieurs questions sur cette demande.

> générer quand on ajoute un courriel dans une offre d'emploi 

Je ne comprends pas bien de quoi il s'agit. Normalement, les instructions de confirmation de compte sont envoyées à la personne qui vient de s'inscrire (que ce soit en postulant à une offre ou non), afin qu'elle confirme son adresse email. À quel moment / endroit peut-on ajouter un courriel dans une offre d'emploi ?

> Vous avez notifié comme « Rôle » dans une offre d’emploi sur le site de recrutement [URL site en fonction de l’environnement].

Cette phrase me paraît incorrecte. On devrait dire "Vous avez été notifié", non ? Par ailleurs, que signifie "Rôle" ici ? Faut-il remplacer ce mot par une valeur ? Laquelle ?

Merci :pray:

**Comment by Queenze972** [comment]
@sebastiencarceles 

1. Quand on créé une OE, à la fin on a la possibilité de renseigner de nouvelles adresses mails "Employeur superviseur" et/ou "Grand Employeur" : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/7d9d2837-63e2-453a-8fe4-164bf49c9bea)

Si l'utilisateur n'avait pas encore de comptes dans l'app, alors il reçoit l'email automatique que l'on modifie. 
C'est d'ailleurs le seul moyen, à date, de créer des utilisateurs "GE" et/ou " ES". Et c'est souvent les utilisateurs avec "Aucun Rôle" 

2. Oui, merci beaucoup c'est "Vous avez été notifié" 
Rôle = "Grand Employeur" et/ou "Employeur superviseur" 

A dispo si ce n'est toujours pas clair :)
