### ISSUE TITLE
[BO > modification compte utilisateur] Modification non prise en compte

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1697]
Comportement constaté : 
1. Modification du champ "Courriel" dans le détail d'un compte utilisateur
2. Enregistrement
3. Message de succès "Compte mis à jour"
4. L'adresse mail n'est finalement pas mise à jour. 

Comportement attendu : 
La modification du courriel est prise en compte. C'est le nouvel identifiant de l'utilisateur pour s'authentifier.

**Comment by sebastiencarceles** [comment]
Petite question préalable stp @Queenze972 : normalement, quand on change d'adresse email, la nouvelle adresse email doit recevoir un email de confirmation. C'est seulement après confirmation de la nouvelle adresse que le changement est bien pris en compte.

Dans ce ticket, est-ce que tu as reçu l'email de confirmation et tu l'as confirmé ?

Merci

**Comment by Queenze972** [comment]
@sebastiencarceles Je ne savais pas que le comportement était le suivant : 
1. Màj du courriel 
2. Réception du courriel de confirmation 
3. Confirmation du courriel 
4. Changement du compte 

Après avoir retesté, c'est tout bon ! Merci pour l'explication.
