### ISSUE TITLE
[BO > ADMIN > Comptes utilisateurs] Activer et supprimer un compte désactivé

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1700]
Comportement actuel : 
On peut désactiver un compte actif via la croix dans la tuile. 
On ne peut pas supprimer complétement un compte désactivé. 

Comportement attendu : 

Droit - Uniquement pour les utilisateurs ADMINISTRATEUR 
1. Dans les comptes désactivés, on modifie la croix pour un "v" afin de réactiver un compte. 
2. Pour les comptes désactivés, on supprime le rond qui permet de renvoyer le courriel de confirmation de mdp 
3. Pour les comptes désactivés, on ajoute une icône poubelle pour supprimer définitivement le compte. 

Il n'est pas possible de supprimer un compte actif, l'admin doit d'abord le désactiver. 
Il n'est pas possible de renvoyer le courriel de confirmation à un compte désactivé, il faut d'abord l'activer.

**Analyse :** Quels sont les éléments liés à un compte utilisateur ?

**Comment by sebastiencarceles** [comment]
@Queenze972 , pour la suppression définitive de compte, il faut prendre en compte les contraintes suivantes.

Un compte `Administrator` possède les éléments suivants : 

- un supervisor, qui est un autre `Administrator` => optionnel, pas de souci à la suppression
- un grand employer, qui est un autre `Administrator` => optionnel, pas de souci à la suppression
- des `JobOfferActor`, qui indiquent son rôle pour des `JobOffer` => **devraient être supprimés ou réaffectés à un autre compte lors de la suppression**
- des `Message` échangés avec les candidat·es => **devraient être supprimés ou réaffectés à un autre compte lors de la suppression**
- des `PreferredUserList`, qui lui permettent de lister des candidat·es dans son vivier => peuvent être détruites

Donc lors de la suppression d'un compte, on doit donc répondre à la question suivante : faut-il supprimer ses messages et ses rôles sur les offres ?

- si on juge que c'est acceptable, alors c'est plutôt facile et vite fait. Il n'y a pas de problème technique particulier.
- si on juge qu'on doit garder sa correspondance avec les candidat·es ainsi que les rôles sur les offres, alors il faut les affecter à un autre compte. On peut le faire au moyen d'une modale, contenant un champ select avec les autres comptes admin => il faut alors sélectionner un compte auquel réaffecter ces données afin de pouvoir effectuer la suppression.

Qu'en penses-tu @Queenze972 ? Si ce n'est pas assez clair ici, discutons-en à l'oral. Merci

**Comment by Queenze972** [comment]
@sebastiencarceles merci pour ton analyse et l'explication. 
OK pour la suppression des rôles sur l'offre, RAS côté fonctionnel. En revanche, si je comprends bien pour les messages : si cet utilisateur a envoyé des messages via l'application aux candidats, nous n'aurons pas l'historique si le compte est supprimé ?

**Comment by sebastiencarceles** [comment]
> si cet utilisateur a envoyé des messages via l'application aux candidats, nous n'aurons pas l'historique si le compte est supprimé ?

J'ai effectué quelques tests. Lorsque le compte admin est supprimé, les messages dont il est l'auteur sont conservés et s'affichent sous cette forme : 
![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/e51421c4-fef2-41a8-8e1c-e01cac30ad9c)

**Comment by Queenze972** [comment]
@sebastiencarceles c'est OK pour moi comme fonctionnement sur l'historique des messages liés à un compte user supprimé, merci pour les tests.
