### ISSUE TITLE
[BO > Paramètres > Valeurs par défaut] Ajouter un renvoi "Myjobglasses"

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1728]
**Comportement attendu :** 
- Ajouter un renvoi vers Myjobglasses comme ci dessous : 

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/ea0e3782-f459-4c49-bc07-01d72b665f13)

_SCENARIO 1 :_ 
Pour se faire, il faudrait optimiser les éditeurs de texte présents dans le SI pour pouvoir ajouter un lien hypertexte et une image dans les valeurs paramétrables : 

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/773d9b72-6e13-4d98-a611-9cb20eed1ac1)

_SCENARIO 2 :_
Ajouter cette mention dans le dur à la fin de chaque offre d'emploi : 
Rencontrez nos ambassadeurs et découvrez tous les métiers du Ministère des Armées 
LOGO MYJOBGLASSES 
https://www.myjobglasses.com/search?q=civil+de+la+d%C3%A9fense

**Comment by sebastiencarceles** [comment]
On privilégie l'ajout de liens dans l'éditeur riche Trix. 
https://trix-editor.org/
Attention il faudrait ça reste sous 1 journée de dev max

**Comment by sebastiencarceles** [comment]
@Queenze972 ça semble assez rapide d'ajouter les liens directement dans l'éditeur, mais beaucoup plus long pour les images. Du coup, je retiens plutôt le scénario 2. Reparlons-en si on souhaite faire un ticket "Ajouter les liens et les images à l'éditeur riche".

**Comment by Queenze972** [comment]
@sebastiencarceles Alors on va prendre l'option : optimiser l'éditeur pour que l'on puisse ajouter des liens directement via ce dernier. On n'ajoute pas l'image. C'est OK pour toi ?

**Comment by sebastiencarceles** [comment]
OK c'est bien noté
