### ISSUE TITLE
[BO > VIVIER > modification de l'affichage de la liste des candidats]

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1731]
**Comportement actuel :** 
Actuellement, sous format liste , une carte candidat se matérialise comme ci dessous [page Vivier] : 

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/dbd9fd9e-cae8-43a0-bead-78c08089d215)

NOM Prénom - icône CV si upload par candidats - Poste actuel - Nombre de Candidatures 

**Comportement attendu :** 
![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/6d798766-105d-4068-a934-bc958f9299de)

Il s'agirait comme sur la maquette de mentionner les informations suivantes : 
NOM Prénom - icône CV si upload par candidats - Domaine pro/Expérience (cf. #1705) - Diplômes - Candidatures 

Domaine pro/Expérience : reprend le double champ créé dans l'onglet "Mon profil candidat" présent dans l'espace candidat et dans le formulaire de candidature. 
Diplômes : Champ à renseigner dans l'onglet "Mon profil candidat" présent dans l'espace candidat et dans le formulaire de candidature. 
Candidatures : RAS par rapport à l'existant

**Comment by sebastiencarceles** [comment]
@Queenze972 on est d'accord que ce ticket dépend des modifications sur "Mon profil candidat" (#1705) et donc on peut le mettre plutôt en v1.6.0 ?

**Comment by sebastiencarceles** [comment]
@Queenze972 je suis passé un peu vite sur la notion de "Diplôme". On est d'accord que c'est un paramètre qui n'existe pas encore dans l'application, et qu'il faut ajouter ? 

Hormis sur la page "Mon profil candidat", où est-ce qu'il s'exprime ?
- sur le formulaire de candidature ?
- sur la page d'une candidature en back office ?
- dans les exports de candidatures ?
- autre chose ?

**Comment by Queenze972** [comment]
@sebastiencarceles, la notion de Diplôme existe déjà dans l'application mais est nommée "Niveau d'études" : 
![image](https://github.com/user-attachments/assets/efe7e630-17b0-4b1c-ba98-51ca41945312)

On retrouve cette info dans : 
- formulaire de candidature à une OE
- carte candidat dans le BO
