### ISSUE TITLE
[WON'T DO] - [DROITS EMPLOYEURS > accès vivier]

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1734]
**Comportement actuel :** 
Les utilisateurs Employeurs, n'ont accès qu'à un vivier réduit : seulement les candidats ayant postulés à leurs offres d'emplois. 

**Comportement attendu :** 
Les utilisateurs Employeurs ont accès à un vivier représentant les candidats : 
- Ayant postulé à l'une de leurs offres d'emploi 
- A l'étape de recrutement : Refusé, Refusé après entretien tél, rencontré mais refusé. 

RG : 
Attention, il faut donc prendre l'étape la plus haute du processus de recrutement. Exemple : Candidat X sur l'offre X à l'état "Nouveau" et Candidat X sur l'offre Z à l'état "Refusé". C'est l'état "Refusé" qui prévaut, le candidat X est donc présent dans le vivier de l'employeur.

**Comment by sebastiencarceles** [comment]
> Les utilisateurs Employeurs, n'ont accès qu'à un vivier réduit : seulement les candidats ayant postulés à leurs offres d'emplois.

@Queenze972 je ne constate pas ce comportement.

En effet, par exemple ici, je suis authentifié avec un compte Employeur :  

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/f854e9c1-8b7d-4ae8-a475-f3b65c2afa78)

Comme on le voit, il y a 37 candidats, ce qui correspond au nombre total de users en base de données.

En particulier, il y a ce premier candidat dans mon vivier : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/33f52871-9860-46cb-b321-313572516a88)

Si je vais regarder son profil, il a candidaté à une offre : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/44d3fbe9-3bff-47b2-84df-df12db6bd242)

Mais je n'ai pas accès à cette offre, car n'est pas une des miennes : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/3b6514df-6d3b-4c5b-b341-2d2d6d2d803e)


Donc comme on le voit dans cet exemple, en tant qu'employeur, j'ai bien accès au vivier complet.

Autre exemple, si je m'authentifie avec le compte employeur "chef@example.com" sur CVD staging, j'accède bien dans le vivier à 159 candidats, c'est à dire l'intégralité de la base. Pourtant, je n'ai publié aucune offre.

J'ai peut-être mal compris la demande ici. Peux-tu revenir vers moi stp ? Merci

**Comment by Queenze972** [comment]
Bonjour @sebastiencarceles , donc actuellement le comportement est : 
L'utilisateur Employeur voit, dans son vivier, tous les candidats ayant postulés à une offre d'emploi tous employeurs confondus ? 

J'ai du être biaisée par le peu de données en PREPROD, désolée.

**Comment by sebastiencarceles** [comment]
> L'utilisateur Employeur voit, dans son vivier, tous les candidats ayant postulés à une offre d'emploi tous employeurs confondus ?

Tout à fait @Queenze972

**Comment by Queenze972** [comment]
@sebastiencarceles Merci pour les précisions. 

L'employeur ne devrait pas avoir les candidats "Retenu" sur d'autres offres que les siennes, dans son vivier de candidats. Cela ne lui sert pas. 
C'est possible donc, juste d'exclure cette catégorie dans la vivier de candidats d'un employeur ?

**Comment by sebastiencarceles** [comment]
@Queenze972 je pense que je ne comprends pas bien le use case ici. Est-ce que ça te va si on aborde ce point à l'oral la semaine prochaine ?

**Comment by sebastiencarceles** [comment]
@Queenze972 Suite à notre échange oral à ce sujet : 
- on garde le ticket dans le projet, pour l'historique et l'analyse
- on ne fait pas de développement en réponse à ce ticket
- on fera un nouveau ticket pour développer la demande de ton dernier message : 

> L'employeur ne devrait pas avoir les candidats "Retenu" sur d'autres offres que les siennes, dans son vivier de candidats. Cela ne lui sert pas.

Est-ce que tu veux bien te charger d'écrire ce ticket ? Et le mettre dans ce projet ou dans un prochain, selon ce qui te semble le mieux.
