### ISSUE TITLE
[BO > Comptes utilisateurs "Aucun rôle"] Assigner un rôle

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1735]
**Comportement actuel :** 
Quand **un utilisateur sans compte configuré** est mentionné dans une offre d'emploi à l'emplacement "3.1 Acteurs du processus notifiés" dans le champ "Courriel" des sections "Employeur" ; "Grand Employeur" ; "RH" ; "CMG" il apparait comme "Aucun rôle" dans la liste des utilisateurs : 

![Image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/155562762/dc427728-afef-4eba-bf5b-011b8d9f3150)

**Comportement attendu :**
Dès qu'un utilisateur sans compte configuré est ajouté dans une offre d'emploi  à l'emplacement "3.1 Acteurs du processus notifiés" dans le champ "Courriel" des sections "Employeur" ; "Grand Employeur" ; "RH" ; "CMG" alors le rôle est mentionné. 
Exemple : insertion d'une adresse mail non connue en BDD dans le champ "Grand Employeur" et enregistrement de l'offre alors le rôle "Grand Employeur" est mentionné à la place de "Aucun rôle".

**Comment by sebastiencarceles** [comment]
Faire une analyse plus précise sur les rôles des admins, les `JobOfferActor` et les possibilités d'affichage.

**Comment by sebastiencarceles** [comment]
@Queenze972 les `Administrator` possèdent un rôle, qui peut avoir la valeur suivante : 
- admin
- employer
- aucun

Ensuite, un `Administrator` possède aussi 0, 1 ou plusieurs `JobOfferActor`. Ce modèle représente le rôle de l'`Administrator` une offre d'emploi donnée. Dans ce cas, le rôle peut être : 
- supervisor_employer
- grand_emploer
- employer
- brh
- cmg

(il ne peut pas être vide)

Dans l'écran présenté ci-dessus en capture d'écran, le rôle affiché est celui de l'`Administrator`, donc "employer" ou "admin".

On pourrait également y ajouter les rôles spécifiques sur les offres d'emploi, mais si une personne est référencée sur de nombreuses offres, elle pourrait avoir les cinq rôles. Est-ce que c'est intéressant d'avoir un résumé ? Par exemple : 

![image](https://github.com/Bureau-Systeme-d-Information-BSI/civilsdeladefense/assets/1193334/3aeba538-bb63-4a9b-93a8-ee4a46516b3d)

Ou alors on remplace le rôle de l'`Administrator` par ses rôles sur les offres d'emploi ? Tout en gardant à l'esprit que si on a les cinq rôles à afficher, ça fait gros dans la ligne, mais on devrait trouver le moyen de tous les afficher.

**Comment by sebastiencarceles** [comment]
@Queenze972 pourras-tu me donner ton avis sur ce sujet stp ? Merci

**Comment by Queenze972** [comment]
@sebastiencarceles Je ne crois pas avoir tout saisi. 

Sur les différents rôles "ADMIN", OK, ça dépend s'ils ont des Offres attachées. 

En revanche, c'est la mention "Aucun rôle" que je ne comprends pas dans la capture d'écran 
![image](https://github.com/user-attachments/assets/e44506f1-984a-48d5-ab15-0162d67a3ab3)

C'est ce tag qui doit être transformé pour mentionner l'un des rôles suivants : 
- Admin 
- Employeur
- CMG
- RH

**Comment by sebastiencarceles** [comment]
Après échange à l'oral, on retient la proposition suivante pour l'implémentation : 

![Image](https://github.com/user-attachments/assets/2a5e2f79-03f3-448f-9738-0e1b50e043f0)

à la différence qu'on affiche tous les rôles de `JobOfferActor` de la personne.
