### ISSUE TITLE
[BUG PROD] Impossible de passer un candidat à l'état "RETENU" 

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1739]
@sebastiencarceles on rencontre actuellement un problème en environnement de production : l'impossibilité de passer une candidate à l'état "RETENU". 

**ENV :** PROD 
**OFFRE** : SID 1744 CONDUCTEUR D'OPERATION EN PCO PÔLE DE BESANCON F/H.
**CANDIDAT** : xxxxxxxxxxxxxx

Étapes pour reproduire le bug : 

# CAS d'USAGE n°1
1. Aller dans les candidatures de l'offre 
2. Sélectionner la carte candidat xxxxxxxxxxxxxx
3. La passer dans la colonne "RETENU" = OK
4. Sortir de la page de l'offre 
5. Revenir sur le trello de l'offre correspondante => La candidate n'est plus dans la colonne "RETENU" 

# CAS d'USAGE n°2
1. Aller dans le détail de la fiche candidat xxxxxxxxxxxxxx
2. Sélectionner "RETENU" dans la liste déroulante dans l'encart droit 
3. PAGE D'ERREUR 500

Merci d'avance pour l'investigation.

**Comment by sebastiencarceles** [comment]
@Queenze972 il y avait une erreur sur les pièces jointes de la candidature. Deux d'entre elles n'avaient pas de type ni de contenu. Ça provoquait une erreur.

Je ne sais pas bien comment on a pu en arriver là. Je soupçonne un problème avec Outscale, comme souvent en la matière. J'ai corrigé manuellement les données et j'ai pu passer la candidature dans "RETENU".

Note : je retire le nom de la personne du ticket, car celui-ci est accessible publiquement.

**Comment by Queenze972** [comment]
Merci beaucoup pour ton retour rapide à ce sujet @sebastiencarceles. 
C'est quand même embêtant si c'est un problème Outscale. J'en parlerai à SCALINGO.
