### ISSUE TITLE
[BUG PROD] Impossible d'archiver 2 Offres d'emplois 

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1784]
Environnement : PROD 
Utilisateurs : ADMINISTRATEUR 

Offres d'emplois concernées : 
- EMAE223 – DESSINATEUR CONCEPTEUR
- EMAE226 – URBANISTE SYSTEME D’INFORMATION 

Lorsque l'on souhaite archiver les offres susmentionnées, le pop-up de sélection d'un motif d'archivage s'affiche, à la sélection d'un motif puis "ARCHIVER" => rien ne se passe.

![image](https://github.com/user-attachments/assets/4639d9bf-6066-47a2-bc4f-353f823adad3)

**Comment by sebastiencarceles** [comment]
@sebastiencarceles  Correspond à l'erreur 500 suivante : https://www.rorvswild.com/applications/136162/errors/54009170?range=1h
