### ISSUE TITLE
Profil 4 : domaines professionnels et expériences

### ISSUE THREAD

**Issue by sebastiencarceles** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1792]
# Contexte

On a déjà la notion de domaine professionnel (`Category`) et celle de niveau d'expérience (`ExperienceLevel`).

# Problème

Les candidats ne peuvent pas avoir de niveau d'expérience différent par domaine professionnel.

# Solution

Pour permettre aux candidats d'avoir des niveaux d'expériences différents selon les domaines professionnels, on créer un modèle `CategoryLevel`) qui associe les deux.

# Impacts

La page "Mon profil candidat" permet l'édition des domaines professionnels et des niveaux d'expérience, tel que décrit par #1705.

Le formulaire de candidature permet l'édition des domaines professionnels et des niveaux d'expérience, tel que décrit par #1706.

En back office, les domaines et expériences sont visibles, tel que décrit par #1731 ET #1705.

**Comment by sebastiencarceles** [comment]
@Queenze972 pour relecture stp

**Comment by Queenze972** [comment]
Ce champ a un caractère obligatoire
- Message d'erreur si enregistrement de la page
