### ISSUE TITLE
Profil 5 : documents

### ISSUE THREAD

**Issue by sebastiencarceles** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1793]
# Contexte

Actuellement les documents sont rattachés à la candidature. Lorsqu'une personne candidate :
- soit c'est sa première candidature : elle doit uploader les documents
- soit ce n'est pas sa première candidature : elle peut uploader les documents ou choisir les documents uploadés lors des précédentes candidatures

# Problème

On souhaite permettre aux candidats de gérer leurs documents sur la page "Mon profil candidat".

**Comment by sebastiencarceles** [comment]
@Queenze972 je me suis arrêté là dans la rédaction car je n'ai pas bien compris, dans #1705 et #1706, ce qu'on souhaite changer à ce sujet. Peux-tu m'en dire plus stp ? Ou bien on fait une réunion dédiée à ce sujet dans le courant du mois prochain ?

**Comment by Queenze972** [comment]
@sebastiencarceles concernant les documents : 

Actuellement en PROD : 
![image](https://github.com/user-attachments/assets/23640870-3ec9-42d4-a1c2-207ec4d7fa6d)
 
Pas de prise en compte du ticket #1634 , que l'on a mis en stand by car compliqué sans mise à niveau de la version du DSFR

Dans le nouveau formulaire "Profil candidat", l'on doit juste voir apparaitre l'upload du CV + mention obligatoire de ce dernier (*).

A ta dispo si besoin de plus de précisions !
