### ISSUE TITLE
[Suite #1777] Ajout de l'information des rôles dans l'export des utilisateurs 

### ISSUE THREAD

**Issue by Queenze972** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#1798]
Suite du ticket #1777 

Ajout de l'information "Rôles sur les offres" dans l'export des comptes utilisateurs 
![Uploading image.png…]()

**Comment by sebastiencarceles** [comment]
@Queenze972 pour info la capture d'écran semble KO dans ce ticket
