### ISSUE TITLE
Back : créer une rubrique "informations" 

### ISSUE THREAD

**Issue by Grainedepaillette** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#678]
- Mettre à disposition des utilisateurs minArm une rubrique à partir de laquelle ils auraient accès à l'adresse de contact s'ils rencontrent un problème. 
- Prévoir également la possibilité de téléverser des P.J (exemple : guides utilisation outil, métier, etc.) voire du contenu vidéo (tutoriels)
- Cette page doit être paramétrable par le BANT

**Comment by Grainedepaillette** [comment]
@btrd Ce ticket renvoie au #1044

sauf qu'il a 2 différences : 
1) Pouvoir télé-verser plusieurs P.j 
2) Pouvoir télé-verser du contenu MP4

Tu pourrais me dire quel est le temps de travail pour ce ticket ? Merci.

**Comment by btrd** [comment]
J'ai compris que l'on dois pouvoir téléverser des PDF, images et vidéos. Par contre ce n'est pas spécifié ce qu'il faut faire avec ce contenu.

Je pense qu'une maquette fonctionnelle peux m'aider à mieux comprendre.
