### ISSUE TITLE
Pouvoir naviguer entre les candidats via des flèches

### ISSUE THREAD

**Issue by jtledoux** [Bureau-Systeme-d-Information-BSI/civilsdeladefense#734]
Intégrer des flèches lorsu'on visualise la fiche candidat depuis la page "offres d'emplois" pour passer à la candidature suivante / précédente

**Comment by btrd** [comment]
@Grainedepaillette On parle bien de cette page ?

<img width="1072" alt="Capture d’écran 2021-07-03 à 09 49 22" src="https://user-images.githubusercontent.com/1385737/124347263-f3d7d700-dbe3-11eb-8af9-73928b00e4f4.png">

**Comment by Grainedepaillette** [comment]
@btrd Oui je confirme, le système doit être disponible pour chacune des colonnes dès lors que l'on au moins 2 cartes candidats.
